<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>Spectre.Console Container Extensions</Title>
    <Description>Extensions for common code and patterns when using Spectre.Console CLI app framework. 

The current release contain implementations of ITypeRegistrar and ITypeResolver to integrate the Autofac, Lamar, LightInject, Ninject, and SimpleInjector dependency injection frameworks with Spectre.Console.</Description>
    <Copyright>Copyright (c) d20Tek</Copyright>
    <PackageProjectUrl>https://github.com/d20Tek/Spectre.Console.Extensions</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/d20Tek/Spectre.Console.Extensions</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>Spectre; Spectre.Console; CLI; dependency injection; autofac; lamar; LightInject; Ninject</PackageTags>
    <PackageReleaseNotes>Split off additional dependency injection containers into this package to minimize dependencies in the core package.</PackageReleaseNotes>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\D20Tek.Spectre.Console.Extensions\D20Tek.Spectre.Console.Extensions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" />
    <PackageReference Include="Lamar" />
    <PackageReference Include="LightInject" />
    <PackageReference Include="Ninject" />
    <PackageReference Include="SimpleInjector" />
    <PackageReference Include="Spectre.Console" />
    <PackageReference Include="Spectre.Console.Cli" />
  </ItemGroup>

</Project>
