name: nuget-publish

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Verify commit exists in origin/main
      run: git branch --remote --contains | grep origin/main

    - name: Extract release notes
      run: |
        git log --pretty=format:'%d %s' ${GITHUB_REF} | perl -pe 's| \(.*tag: v(\d+.\d+.\d+(-preview\d{3})?)(, .*?)*\)|\n## \1\n|g' > RELEASE-NOTES

    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.x

    - name: Build
      run: dotnet build --configuration Release /p:Version=${VERSION}

    - name: Test
      run: dotnet test --configuration Release /p:Version=${VERSION} --no-build

    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build --output .

    - name: Publish Spectre.Console.Extensions (local)
      run: dotnet nuget push D20Tek.Spectre.Console.Extensions.${VERSION}.nupkg --source https://nuget.pkg.github.com/d20Tek/index.json --api-key ${GITHUB_TOKEN}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish Spectre.Console.Extensions.MoreContainers (local)
      run: dotnet nuget push D20Tek.Spectre.Console.Extensions.MoreContainers.${VERSION}.nupkg --source https://nuget.pkg.github.com/d20Tek/index.json --api-key ${GITHUB_TOKEN}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish Spectre.Console.Extensions (nuget.org)
      run: dotnet nuget push D20Tek.Spectre.Console.Extensions.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_API_KEY}
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

    - name: Publish Spectre.Console.Extensions.MoreContainers (nuget.org)
      run: dotnet nuget push D20Tek.Spectre.Console.Extensions.MoreContainers.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_API_KEY}
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
